name: ${project.artifactId}
version: ${project.version}
main: net.jonnegaming.nodurability.NoDurability
load: POSTWORLD
author: "Aleksi220"
api-version: '${apiVersion}'
softdepend: [PlaceholderAPI]
permissions:
  nodurability.use:
    default: true
