name: NoDurability
version: 1.0
main: net.jonnegaming.nodurability.NoDurability
load: POSTWORLD
author: "Aleksi220"
api-version: '1.21'
softdepend: [PlaceholderAPI]
permissions:
  nodurability.use:
    default: true
