name: NoDurability
version: 1.0
main: net.jonnegaming.nodurability.NoDurability
load: POSTWORLD
author: "Aleksi220"
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  removedurability:
    aliases:
      - "removedura"
      - "rmdurability"
      - "rmdura"
    permission: "removedurability.rm"
    usage: "/<command>"
permissions:
  removedurability.*:
    default: "op"
    children:
      ["removedurability.rm", "true"]
  removedurability:rm:
    default: "op"
